CREATE TABLE pessoa(

	id INT NOT NULL AUTO_INCREMENT,
	cpf NVARCHAR(11) NOT NULL,
	nome NVARCHAR(150) NOT NULL,
	email NVARCHAR(150) NOT NULL,
	idade INT NOT NULL,
	sexo NVARCHAR(25) NOT NULL,
	PRIMARY KEY (id)
);